### ISSUE TITLE
ToDos before merging transloc_new_genetics_merge into other branches

### ISSUE THREAD

**Issue by JetteReeg** [RangeShifter/RScore#79]
- [x]  sampledInds used for both NeutralStatistics and Translocation: check whether there is an issue
- [x] gNameCostFile vs. name_costfile: what should be kept?
- [x] is there a status = 10 in the new genetics? ("cold storage")'? I used status 10 for translocated individuals

**Comment by JetteReeg** [comment]
It should be fine to use sampledInds as storage for NeutralStatsManager and Translocation because they are cleared every time the function is called.

I could not find any code that uses 10 for setting a status of an individual except for the translocation. So that should also be fine.

**Comment by TheoPannetier** [comment]
A bit late on this but I just wanted to confirm - individual status 10 is indeed not used and available for translocation. It was at some point reserved for a "cold storage" feature but since the feature wasn't completely developed and I couldn't find any doc on what it was expected to do I just scrapped it.
